#!/bin/bash

cat | plc --values | \
fzf -e -m --info=inline --ansi --color="hl:51" --no-sort --layout=reverse-list --color="header:39" "${@}" \
	--bind='alt-k:preview-up' --bind='alt-j:preview-down' \
	--bind='?:toggle-preview' \
	--preview-window='top:50%' \
	--preview '\
		file=$(arg_n 1 {}) line=$(arg_n 2 {}) line=${line:-1} && \
		echo "$file" | plc && \
			[[ -d "$file" ]] && ls -AgGh --group-directories-first --color=always "$file" \
			|| tvcat "$file" $((line + 50)) | sed -n -e "s/^/ /" -e "${line}s/^./\x1B[93m»\x1B[m/" -e "$(minus_limit $line 10 1),\$p"'

