#!/bin/bash

cat | plc --values | \
fzf -e -m --info=inline --ansi --color="hl:51,hl+:51" --no-sort --layout=reverse-list --color="header:39" \
	--bind='alt-k:preview-up' --bind='alt-j:preview-down' \
	--bind='?:toggle-preview' \
	--preview-window='top:50%' "${@}" \
	--preview '\
		file=$(arg_n 1 {}) line=$(arg_n 2 {}) line=${line:-1} range_start=$(minus_limit $line 10 1) && \
		echo "$file" | plc && \
			[[ ! -d "$file" ]] && tvcat "$file" | sed -n "$range_start,10000p" | sed -e "s/^/   /" -e "$((($line - $range_start) + 1))s/^   />> /" \
			|| ls -AgGh --group-directories-first --color=always "$file"'

			# [[ ! -d "$file" ]] && bat --theme="TwoDark" --highlight-line $line --tabs=4 -n --color=always "$file" -r $(minus_limit $line 4 1): \
