#!/bin/bash
(([[ -t 0 ]] && fd --type f -H --color=always) || cat) | rg -L -v '.git(\u001B\[[0-9;m]+)*/' | \
	fzf -e -m --info=inline --layout=reverse $* --ansi --preview 'bat --line-range 0:100 --tabs=4 -n --color=always {}' --color="hl:51" 
