#!/bin/bash

# pick from list, with exact match, preview

(([[ -t 0 ]] && fd --type f -H --color=always) || cat) | rg -L -v '.git(\u001B\[[0-9;m]+)*/' | \
	fzf -e -m --info=inline --layout=reverse $* --ansi --preview 'tvcat {}' --color="hl:51" 
